{% set version = '0.1.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-oyster
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/oysteR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/oysteR/oysteR_{{ version }}.tar.gz
  sha256: 27d3785e784806bc0b636948162bece91386f40080b4c811840484045349ef87

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-dplyr
    - r-glue
    - r-httr
    - r-jsonlite
    - r-purrr
    - r-rjson
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-yaml
  run:
    - r-base
    - r-cli
    - r-dplyr
    - r-glue
    - r-httr
    - r-jsonlite
    - r-purrr
    - r-rjson
    - r-rlang
    - r-stringr
    - r-tibble
    - r-tidyr
    - r-yaml

test:
  commands:
    - $R -e "library('oysteR')"           # [not win]
    - "\"%R%\" -e \"library('oysteR')\""  # [win]

about:
  home: https://github.com/sonatype-nexus-community/oysteR
  license: Apache-2.0
  summary: Collects a list of your third party R packages, and scans them with the 'OSS' Index
    provided by 'Sonatype', reporting back on any vulnerabilities that are found in
    the third party packages you use.
  license_family: APACHE
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: oysteR
# Title: Scans R Projects for Vulnerable Third Party Dependencies
# Version: 0.1.1
# Authors@R: c(person(given = "Jeffry", family = "Hesse", role = "aut", email = "jhesse@sonatype.com"), person(given = "Brittany", family = "Belle", role = "aut", email = "bbelle@sonatype.com"), person(given = "Colin", family = "Gillespie", role = c("aut", "cre"), email = "csgillespie@gmail.com", comment = c(ORCID = "0000-0003-1787-0275")), person(given = "Dan", family = "Rollo", role = "aut", email = "drollo@sonatype.com"), person(given = "Josiah", family = "Parry", role = "ctb", email = "josiah.parry@gmail.com"), person(given = "Sonatype", role = "cph"))
# Maintainer: Colin Gillespie <csgillespie@gmail.com>
# Description: Collects a list of your third party R packages, and scans them with the 'OSS' Index provided by 'Sonatype', reporting back on any vulnerabilities that are found in the third party packages you use.
# License: Apache License 2.0 | file LICENSE
# URL: https://github.com/sonatype-nexus-community/oysteR
# BugReports: https://github.com/sonatype-nexus-community/oysteR/issues
# Depends: R (>= 3.5.0)
# Imports: cli, dplyr, glue, httr, jsonlite, purrr, rjson, rlang, stringr, tibble, tidyr, utils, yaml
# Suggests: covr, httptest, knitr, rmarkdown, testthat (>= 2.1.0)
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# NeedsCompilation: no
# Packaged: 2021-01-09 19:25:26 UTC; ncsg3
# Author: Jeffry Hesse [aut], Brittany Belle [aut], Colin Gillespie [aut, cre] (<https://orcid.org/0000-0003-1787-0275>), Dan Rollo [aut], Josiah Parry [ctb], Sonatype [cph]
# Repository: CRAN
# Date/Publication: 2021-01-10 15:20:06 UTC
